### ISSUE TITLE
《音乐标签》应用编辑后解析报错

### ISSUE THREAD

**Issue by yhsj0919** [ijinfeng/id3_codec#1]
版本V1，Genre被重置为255，导致genreList数组越界

**Comment by ijinfeng** [comment]
> 版本V1，Genre被重置为255，导致genreList数组越界

这个问题今天已经修复了，你更新下就好

**Comment by ijinfeng** [comment]
> > 版本V1，Genre被重置为255，导致genreList数组越界
> 
> 这个问题今天已经修复了，你更新下就好

最新版本是0.0.10，感谢支持
