### ISSUE TITLE
哥们可以支持读写歌词标签嘛

### ISSUE THREAD

**Issue by coolight7** [ijinfeng/id3_codec#3]
* 很需要读写歌词LYRIC标签的功能，如果可以的话希望得到支持！
* 能支持读写就行，解析歌词小问题，当然您一条龙服务我也很开心嘿嘿！

**Comment by ijinfeng** [comment]
> * 很需要读写歌词LYRIC标签的功能，如果可以的话希望得到支持！
> * 能支持读写就行，解析歌词小问题，当然您一条龙服务我也很开心嘿嘿！

歌词标签有同步SYLT，我看是支持读的，你要支持写的话，你发我一份带有歌词的音频文件，我有时间看下

**Comment by coolight7** [comment]
> > * 很需要读写歌词LYRIC标签的功能，如果可以的话希望得到支持！
> > * 能支持读写就行，解析歌词小问题，当然您一条龙服务我也很开心嘿嘿！
> 
> 歌词标签有同步SYLT，我看是支持读的，你要支持写的话，你发我一份带有歌词的音频文件，我有时间看下

* 是的，读取ID3的歌词出来是支持的，只是不支持写。
* 之前使用的时候发现读不了歌词，刚刚发现基本上是flac等非mp3格式时读取没有信息（不止歌词，任何信息都没有），然后了解到是flac等文件普遍使用的是apev2而非id3，我想我的需求应该是希望支持读apev2。咱这个有支持apev2的计划嘛

* 包含内置歌词的MP3文件：
http://mycos-res.mimicry.cool/temp/%E5%91%A8%E6%9D%B0%E4%BC%A6%20-%20%E7%AD%89%E4%BD%A0%E4%B8%8B%E8%AF%BE%20%28with%20%E6%9D%A8%E7%91%9E%E4%BB%A3%29.mp3
* 包含内置歌词的flac文件：
http://mycos-res.mimicry.cool/temp/%E5%91%A8%E6%9D%B0%E4%BC%A6%20-%20%E7%AD%89%E4%BD%A0%E4%B8%8B%E8%AF%BE%28with%20%E6%9D%A8%E7%91%9E%E4%BB%A3%29.flac

**Comment by ijinfeng** [comment]
这个库只支持id3，设计的时候就只考虑了id3，后期也不会去支持apev2。如果你希望是支持apev2的歌词读写，那只能找别的库看看了

**Comment by ijinfeng** [comment]
> > > * 很需要读写歌词LYRIC标签的功能，如果可以的话希望得到支持！
> > > * 能支持读写就行，解析歌词小问题，当然您一条龙服务我也很开心嘿嘿！
> > 
> > 
> > 歌词标签有同步SYLT，我看是支持读的，你要支持写的话，你发我一份带有歌词的音频文件，我有时间看下
> 
> * 是的，读取ID3的歌词出来是支持的，只是不支持写。
> * 之前使用的时候发现读不了歌词，刚刚发现基本上是flac等非mp3格式时读取没有信息（不止歌词，任何信息都没有），然后了解到是flac等文件普遍使用的是apev2而非id3，我想我的需求应该是希望支持读apev2。咱这个有支持apev2的计划嘛
> * 包含内置歌词的MP3文件：
>   http://mycos-res.mimicry.cool/temp/%E5%91%A8%E6%9D%B0%E4%BC%A6%20-%20%E7%AD%89%E4%BD%A0%E4%B8%8B%E8%AF%BE%20%28with%20%E6%9D%A8%E7%91%9E%E4%BB%A3%29.mp3
> * 包含内置歌词的flac文件：
>   http://mycos-res.mimicry.cool/temp/%E5%91%A8%E6%9D%B0%E4%BC%A6%20-%20%E7%AD%89%E4%BD%A0%E4%B8%8B%E8%AF%BE%28with%20%E6%9D%A8%E7%91%9E%E4%BB%A3%29.flac

这个库只支持id3，设计的时候就只考虑了id3，后期也不会去支持apev2。如果你希望是支持apev2的歌词读写，那只能找别的库看看了

**Comment by coolight7** [comment]
> > > > * 很需要读写歌词LYRIC标签的功能，如果可以的话希望得到支持！
> > > > * 能支持读写就行，解析歌词小问题，当然您一条龙服务我也很开心嘿嘿！
> > > 
> > > 
> > > 歌词标签有同步SYLT，我看是支持读的，你要支持写的话，你发我一份带有歌词的音频文件，我有时间看下
> > 
> > 
> > 
> > * 是的，读取ID3的歌词出来是支持的，只是不支持写。
> > * 之前使用的时候发现读不了歌词，刚刚发现基本上是flac等非mp3格式时读取没有信息（不止歌词，任何信息都没有），然后了解到是flac等文件普遍使用的是apev2而非id3，我想我的需求应该是希望支持读apev2。咱这个有支持apev2的计划嘛
> > * 包含内置歌词的MP3文件：
> >   http://mycos-res.mimicry.cool/temp/%E5%91%A8%E6%9D%B0%E4%BC%A6%20-%20%E7%AD%89%E4%BD%A0%E4%B8%8B%E8%AF%BE%20%28with%20%E6%9D%A8%E7%91%9E%E4%BB%A3%29.mp3
> > * 包含内置歌词的flac文件：
> >   http://mycos-res.mimicry.cool/temp/%E5%91%A8%E6%9D%B0%E4%BC%A6%20-%20%E7%AD%89%E4%BD%A0%E4%B8%8B%E8%AF%BE%28with%20%E6%9D%A8%E7%91%9E%E4%BB%A3%29.flac
> 
> 这个库只支持id3，设计的时候就只考虑了id3，后期也不会去支持apev2。如果你希望是支持apev2的歌词读写，那只能找别的库看看了

好的谢谢
